apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
   - apiGroups:
       - cilium.io
     kinds:
       - CiliumIdentity
     clusters:
       - "*"
  url: https://argo.jindrich-jakubicka.cz
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: e840a3281000058d21c5
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: Jindra-Dev04
