apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: majnr-minecraft
  namespace: majnr
spec:
  entryPoints:
    - minecraft
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: kostky-minecraft
      port: 25566
