traefik:
  certResolvers:
    letsencrypt:
      # for challenge options cf. https://doc.traefik.io/traefik/https/acme/
      email: j.jakubicka@email.cz
      tlsChallenge: true
      httpChallenge:
        entryPoint: "web"
      # It has to match the path with a persistent volume
      storage: /data/acme.json

  ingressRoute:
    dashboard:
      enabled: true

  additionalArguments:
  - "--ping"
  - "--metrics.prometheus"
  - "--accesslog=true"
  - "--entrypoints.factorio.address=:34197/udp"

  persistence:
    enabled: true
    name: data
    accessMode: ReadWriteOnce
    size: 128Mi
    path: /data

  service:
    externalIPs:
    - 192.168.8.170

  ports:
    factorio:
      port: 34197
      expose: true
      exposedPort: 34197
      protocol: UDP
