minecraft:

  workloadAsStatefulSet: true
  strategyType: RollingUpdate

  minecraftServer:
    eula: true
    version: "1.20.1"
    type: CURSEFORGE
    difficulty: normal
    cfServerMod: "fabric-server-launch.jar"
    whitelist: 

    servicetype: ClusterIP
    servicePort: 25565
    
  autoCurseForge:
    apiKey:
      existingSecret: curseforge-secret
      key: cf-api-key

    pageUrl: https://www.curseforge.com/minecraft/modpacks/majnr-plus

  persistence:
    dataDir:
      enabled: true
      size: 2Gi
