minecraft:

  workloadAsStatefulSet: true
  strategyType: RollingUpdate

  minecraftServer:
    eula: true
    version: "1.20.1"
    type: AUTO_CURSEFORGE
    difficulty: normal
    whitelist: "gamabe_cz, Mr_Guglik, Sp3lky"
    ops: "gamabe_cz"
    memory: 6G

    serviceType: LoadBalancer
    servicePort: 25505

    rcon:
      enabled: true
      existingSecret: rcon
      secretKey: rcon

    
    autoCurseForge:
      apiKey:
        existingSecret: curseforge-secret
        key: cf-api-key
      includeMods:
        - worldedit

      pageUrl: https://www.curseforge.com/minecraft/modpacks/majnr-plus/files/5131051

  persistence:
    dataDir:
      enabled: true
      size: 2Gi

  mcbackup:
    enabled: true
    backupMethod: rclone
    initialDelay: 5m
    backupInterval: 3h
    pauseIfNoPlayers: "true"
    pruneBackupsDays: 2

    # RClone
    rcloneRemote: s3
    rcloneDestDir: jindra-experiments/majnr
    rcloneConfigExistingSecret: rclone

    persistence:
      backupDir:
        enabled: true
        Size: 3Gi
