minecraft:

  workloadAsStatefulSet: true
  strategyType: RollingUpdate

  minecraftServer:
    eula: true
    version: "1.19.2"
    type: FORGE
    forgeVersion: "43.3.0"
    ops: "gamabe_cz, JackVonTennessee"
    memory: 12G

    # World
    difficulty: hard
    viewDistance: 16
    spawnProtection: 0
    maxWorldSize: 20000
    maxBuildHeight: 320
    levelSeed: "795771997"

    # Service
    serviceType: LoadBalancer
    servicePort: 25565

    rcon:
      enabled: true
      withGeneratedPassword: true

    
    # autoCurseForge:
    #   apiKey:
    #     existingSecret: curseforge-secret
    #     key: cf-api-key
    #   includeMods:
    #     - worldedit

    #   # pageUrl: https://www.curseforge.com/minecraft/modpacks/majnr-plus/files/5131051
    #   slug: "cogs-spells"

  persistence:
    dataDir:
      enabled: true
      size: 20Gi

  livenessProbe:
    initialDelaySeconds: "6000"

  readinessProbe:
    initialDelaySeconds: "1200"
