apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorio-server
  namespace: factorio
spec:
  entryPoints:
    - factorio
  routes:
  - services:
    - name: factorio-factorio-server-charts
      port: 31497