factorio-server-charts:
  image:
    tag: "1.1.100"

  mods:
    enabled: true
    portal: 
      - aai-containers
      - aai-industry
      - aai-signal-transmission
      - alien-biomes
      - Bottleneck
      - bullet-trails
      - calculator-ui
      - cargo-ships
      - cargo-ships-graphics
      - DeadlockBlackRubberBelts
      - EpicArtillerySounds
      - equipment-gantry
      - even-distribution
      - far-reach
      - flib
      - grappling-gun
      - helmod
      - informatron
      - jetpack
      - Krastorio2
      - Krastorio2Assets
      - LogisticTrainNetwork
      - LTN_Content_Reader
      - Mechanicus
      - Mining_Drones
      - NapalmArtillery
      - qol_research_jatmn
      - queue-to-front-button
      - RateCalculator
      - robot_attrition
      - scattergun_turret
      - shield-projector
      - simhelper
      - space-exploration
      - space-exploration-graphics
      - space-exploration-graphics-2
      - space-exploration-graphics-3
      - space-exploration-graphics-4
      - space-exploration-graphics-5
      - space-exploration-postprocess
      - 'Squeak Through'
      - Todo-List
      - Transport_Drones
      - VehicleSnap
      - Waterfill_v17

  service:
    type: ClusterIP
    port: 34197

  factorioServer:
    generate_new_save: false

  account:
    accountSecret: 'account-secret'

  serverPassword:
    passwordSecret: 'game-secret'

  server_settings:
    name: 'As allways'
    require_user_verification: true
    autosave_interval: 5
    tags:
      - 'game'
      - 'factorio'
      - 'server'
      - 'modded'
      - 'as-always'
    visibility:
      public: true
      lan: false

  import_save:
    enabled: false
    source_url: 'https://cdn.discordapp.com/attachments/936038038352592926/1191922726412226580/JakoVzdycky.zip?ex=65a7338a&is=6594be8a&hm=12884b3a018dc43989813abdb8de7d8671b80b3968405576a51148e26a123b21&' 

  rcon:
    external: false
    passwordSecret: 'rcon-secret'

  admin_list:
    - gamabe_cz
    - mugac
